#ifndef EEPROM_DEFINITIONS
#define EEPROM_DEFINITIONS

#define EEPROM_STORED_CARD_COUNTER 0
#define EEPROM_ALARM_BUZZER_STATE 1
#define EEPROM_RAINBOW_ANIMATION_SPEED 3
#define EEPROM_SOUND_REACT_ANIMATION_SENSIBILITY 4
#define EEPROM_VOLUME 5
#define EEPROM_CARDS 11

#endif