#ifndef KEYPAD_FUNCTIONS
#define KEYPAD_FUNCTIONS

#include <Arduino.h>

#define LIGHTS_MENU 1

#define SOFA_LIGHT_CONTROL_SUBMENU 12
#define SOFA_LIGHT_TEMPERATURE_CONTROL_SUBMENU 121
#define SOFA_LIGHT_LUMINOSITY_CONTROL_SUBMENU 122
#define SOFA_LIGHT_EFFECT_CONTROL_SUBMENU 123

#define BEDSIDE_LIGHT_CONTROL_SUBMENU 13
#define BEDSIDE_LIGHT_TEMPERATURE_CONTROL_SUBMENU 131
#define BEDSIDE_LIGHT_COLOR_CONTROL_SUBMENU 132
#define BEDSIDE_LIGHT_LUMINOSITY_CONTROL_SUBMENU 133
#define BEDSIDE_LIGHT_EFFECT_CONTROL_SUBMENU 134

#define RGB_STRIP_CONTROL_SUBMENU 15
#define RGB_STRIP_COLOR_CONTROL_SUBMENU 151
#define RGB_STRIP_EFFECT_CONTROL_SUBMENU 152

#define DEVICES_MENU 2

#define TV_MENU 3

#define CONFIGURATION_MENU 4

#define ALARM_CODE_CONFIGURATION_MENU 411
#define ALARM_CONFIGURATION_MENU 41

extern int keypadMenu;
extern String alarmCode;

extern unsigned long pressedKeypadTouchTime;
extern unsigned long keypadSubMenuTimer;

void keypadButtonPressed(char key, boolean longPress);

#endif