#ifndef PIN_DEFINITIONS
#define PIN_DEFINITIONS

// Définition des broches des capteurs.
#define PIN_IR_SENSOR 7
#define PIN_WARDROBE_DOOR_SENSOR 38
#define PIN_RFID_DATA_1_SENSOR 39
#define PIN_RFID_DATA_2_SENSOR 40
#define PIN_DOORBELL_BUTTON 42
#define PIN_BEDROOM_DOOR_SENSOR 43
#define PIN_MUTE_BUTTON 47
#define PIN_CHARGING_STATION_BUTTON 50
#define PIN_TEMPERATURE_SENSOR 54
#define PIN_MICRO 55

// Définition des broches des actionneurs.
#define PIN_BUZZER 2
#define PIN_RED_LED 3
#define PIN_GREEN_LED 4
#define PIN_BLUE_LED 5
#define PIN_IR_LED 6
#define PIN_SCREEN_SERVO 8
#define PIN_TV_RELAY 22
#define PIN_RELAY_8 23
#define PIN_LED_CUBE_RELAY 24
#define PIN_RELAY_7 25
#define PIN_FAN_RELAY 26
#define PIN_RELAY_6 27
#define PIN_ALARM_RELAY 28
#define PIN_WARDROBE_LIGHTS_RELAY 29
#define PIN_ALARM_SIGNAL 41
#define PIN_MOTOR_TRAY_1 44
#define PIN_MOTOR_TRAY_2 45
#define PIN_POWER_SUPPLY 48

#endif